sudo: true
dist: trusty
language: sh
addons:
  apt:
    packages:
      - build-essential

before_script:
  # Show the git version being used to test.
  - "git --version"
  # Show the zsh version being used to test.
  - "zsh --version"

install:
  - "sudo apt-get update -qq"
  - "sudo apt-get install -y zsh"
  - "sudo chsh -s $(which zsh)"
  - "sudo apt-get install -y git mercurial subversion jq node golang ruby python python-virtualenv"

script:
  - test/powerlevel9k.spec
  - test/functions/utilities.spec
  - test/functions/colors.spec
  - test/functions/icons.spec
  - test/segments/command_execution_time.spec
  - test/segments/dir.spec
  - test/segments/rust_version.spec
  - test/segments/go_version.spec
  - test/segments/vcs.spec
  - test/segments/kubecontext.spec
